### ISSUE TITLE
8184.12 DEV - add core services to pipeline

### ISSUE THREAD

**Issue by trriplejay** [Shippable/beta#564]
Shippable/pm#8184

postgres, vault, gitlab, rabbitmq, and redis containers used during onebox install should be pushed to drydock image registry, much like build images.

any change to the drydock repos should trigger a build of the image that pushes to the `master` tag.  when rel-prod is run, the master version should be re-tagged with the release version.

**Comment by stephanielingwood** [comment]
verified postgres, vault, and gitlab after a prod deployment. the lines are drawn correctly for rabbit and redis in the spog, and are the exact same configuration as postgres, gitlab, and vault.
