### ISSUE TITLE
8184.12 DEV - update admiral to commit/push release version

### ISSUE THREAD

**Issue by trriplejay** [Shippable/beta#565]
Shippable/pm#8184

admiral is already tagging and pushing when rel-prod is run, however we want to add some functionality.

- before tagging the repo, we should write the release version to a file
- commit that file and git push it, so that the release version is part of the repo
- continue with the regular tagAndPush script.

**Comment by stephanielingwood** [comment]
this will be verified tonight when the production release is run.

**Comment by stephanielingwood** [comment]
verified with a new install on a DO box.
